### ISSUE TITLE
First roadmap

### ISSUE THREAD

**Issue by carlosmintfan** [hugerte/hugerte#1]
HugeRTE is now up at npm and composer (#25). Some things to do still:
- [x] Forcibly fetch other TinyMCE commits
- [x] Revert https://github.com/hugemce/hugemce/commit/4d8419284fa1c7dd42f006aefe02c936b2cd4a80, https://github.com/hugemce/hugemce/commit/6256d08e9754ede01131cedfbac4cd1be43ddd09 and https://github.com/hugemce/hugemce/commit/6036c3801f299c906c4f924f5f92e4164816106b, also take a look at the version change in https://github.com/hugemce/hugemce/commit/95510dfb93e85d6c65df3278646e3ce6035fffa1
- [x] Bring back deprecated template plugin (and possibly more)
- [x] De/rebranding from Tiny to HugeMCE
- [x] Partly revert https://github.com/hugemce/hugemce/commit/41b743c080db94c35e904b53f784aa85dbc9b4cf until we have a logo; not forget to update the link from Tiny to hugemce.org
- [x] Throw away the upgrade button as our product is 100% free
- [x] make `convert_unsafe_embeds` true by default (we already include the commit)
- [x] i18n
- [x] Take look at security alerts (dependencies...not fixed in TinyMCE 6??)
- [x] Update readme
- [ ] Fork the react, vue and angular stuff and possibly these integrations
- [x] npm
- [x] composer
- [x] jsDelivr (no actions needed, auto pull from npm)
- [x] First website content
- [x] Update website

**Comment by ThiefMaster** [comment]
> Change license to LGPL everywhere

Do you really want to do that? While LGPL is much nicer than pure GPL, IMHO one of the big advantages of "old" TinyMCE was that it was under a permissive license.

**Comment by carlosmintfan** [comment]
> > Change license to LGPL everywhere
> 
> Do you really want to do that? While LGPL is much nicer than pure GPL, IMHO one of the big advantages of "old" TinyMCE was that it was under a permissive license.

I can definitely use MIT if most of you (that is, the commentators of issue 9453 at TinyMCE) would prefer it. The upside of LGPL would be that TinyMCE and other big companies can't sell our work.

**Comment by carlosmintfan** [comment]
I've changed the license to MIT now. This will also make it easier for me so I don't have to change the license in all that js or json or whatever files.

**Comment by mikkorantalainen** [comment]
I think going with MIT is the best because that allows having widest possible user base, which is definitely needed if one wants to compete with the official TinyMCE.

Note that you could merge in patches from the original repo up to commit 282f1ebb24e6dc86da3bf259e0c031ca44518cba because that's the last commit before the license was changed in commit 1cfe7f6817c68d713971a3e1dbe0c9775a40ce6d.

**Comment by mikkorantalainen** [comment]
As for the changes I would love to see in forked codebase:

- Get rid of non-native "functional programming" patterns that simply makes code harder to understand. For example, the class `Optional` could be replaced simply by using the actual value or the JavaScript `undefined` vs `null` everywhere. If you try to single-step any event handler in TinyMCE you'll find that most of the actually executed code in browser JS engine is about continuously mangling data back and forth via these functional programming patterns.
- Get rid of `SugarElement` because modern browsers can do all of that natively without any wrapper classes. Similar problems with class `Optional` above.
- Remove old code that implements polyfills and workarounds for MSIE. There's no sensible way to support MSIE so having any code for that only makes maintaining the code harder.

The most important bugs to fix (IMO):

- https://github.com/tinymce/tinymce/issues/3652
- https://github.com/tinymce/tinymce/issues/6811
- https://github.com/tinymce/tinymce/issues/6352

And I would love to see proper Yjs binding for the editor which would allow for real remote collaboration between multiple authors over WebSocket. Basically HugeMCE counterpart to ProseMirror bindings here: https://github.com/yjs/y-prosemirror – howerver, I'm not sure if anybody else but @dmonad can do this in reality.

**Comment by jlowcs** [comment]
Are there any plans to also fork https://github.com/tinymce/tinymce-react (and possibly the vue and angular ones as well), since it has a peer dependency on `tinymce`?

**Comment by carlosmintfan** [comment]
Dear community, thank you for all your stars to this repo. I hope it will be worth them soon. I hope you don't mind my recent inactivity. I hope to get around to working more at this soon. Anyway, there is still some time until September, so I don't have to rush :)

**Comment by nhuthan** [comment]
Hi, can you give me a little update on the current situation?

**Comment by carlosmintfan** [comment]
Hi @nhuthan, thank you for your interest in this project. I've currently been a bit lazy in regards to this project, but I'll soon update to the latest TinyMCE 6 minor release so we have a stable base.

**Comment by carlosmintfan** [comment]
https://hugemce.org is up now (although there isn't much on it).

**Comment by carlosmintfan** [comment]
It may not be the cleanest way how I'm doing that merge stuff, but I hope it's okay. I fetched the latest commits now.

**Comment by carlosmintfan** [comment]
Should I update the dependencies Dependabot tells me are vulnerable? Then why isn't TinyMCE doing it although v6 is still supported? Hmm.

**Comment by ThiefMaster** [comment]
At least vulnerable dev deps are completely irrelevant 99% of the time

**Comment by carlosmintfan** [comment]
Okay, I'll see. But now:
```
$ yarn
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.
$ yarn build
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'build'
```
???

**Comment by carlosmintfan** [comment]
Even when building TinyMCE 7...hmm, there must be something wrong with my version of yarn. Maybe it'll work when I update to Linux Mint 22 (currently on 21.3)

**Comment by carlosmintfan** [comment]
Sorry, a simple `npm -g update yarn` solved it :)

**Comment by carlosmintfan** [comment]
I'll be building it now and see if there aren't any big issues.

**Comment by carlosmintfan** [comment]
Especially as I've pulled more commits than TinyMCE 6 has

**Comment by Blackbam** [comment]
@carlosmintfan First of all thank you for starting this! The most important thing in my opinion is to integrate fixes for reported vulnerabilities, because it will be an issue for many who are using TinyMCE in commercial projects. Can help with it from time to time hopefully.

**Comment by carlosmintfan** [comment]
So the monorepo namespace for all the modules is not `@tinymce`, it's `@ephox`. Do you think I can call both the namespace `@hugemce` and the project `hugemce`?

**Comment by carlosmintfan** [comment]
@mikkorantalainen https://github.com/hugemce/hugemce/blob/main/modules/sugar/src/demo/ts/ephox/sugar/demo/Demo.ts indeed looks like almost everything could be done natively. Only CSS is maybe cleaner there than with native properties.
The question is, why does Sugar then exist? For old browsers?

**Comment by carlosmintfan** [comment]
Do you think it would be okay it the TinyMCE > HugeMCE move would require a global search-and-replace in your JavaSript? (As opposed to my previous plan.)
Then I could just do a global sed in this repo too before publishing to npm.

**Comment by carlosmintfan** [comment]
Dang, building results in no space left on device LOL

**Comment by carlosmintfan** [comment]
There's both `@ephox/oxide-icons-default` and `@tinymce/oxide-icons-default`, the first being used in tsconfig.json and the rest elsewhere.

**Comment by carlosmintfan** [comment]
Hmmm....
```
Running "shell:tsc" (shell) task
src/core/test/ts/browser/EditorTest.ts(404,28): error TS2339: Property 'type' does not exist on type 'never'.
Warning: Command failed: tsc -b
 Use --force to continue.

Aborted due to warnings.
error Command failed with exit code 6.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "tinymce-grunt" exited with 6.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mikkorantalainen** [comment]
> @mikkorantalainen https://github.com/hugemce/hugemce/blob/main/modules/sugar/src/demo/ts/ephox/sugar/demo/Demo.ts indeed looks like almost everything could be done natively. Only CSS is maybe cleaner there than with native properties. The question is, why does Sugar then exist? For old browsers?

I think you meant https://github.com/hugemce/hugemce/blob/02f35e9a88d0b5156d5680af9eb7dc6d1f8f9c3c/modules/sugar/src/demo/ts/hugemce/sugar/demo/Demo.ts because that URL returns HTTP status 404.

I think the whole Sugar stuff is about the original developer really liking functional languages such as Haskell and they simply wanted to use wrapper that allowed to use more functional-like syntax. However, it causes both extra download and runtime penalty so I think it would make a lot more sense to get rid of such sugar.

If TypeScript were smart enough to actually implement this as pure syntax sugar and the compiled version had none of this crap, I would be perfectly okay with using the Sugar wrapper if somebody actually likes it. I would personally much prefer native JavaScript (ES6+ because it's readable and works with real world browsers) over any TypeScript even for the original source code.

**Comment by carlosmintfan** [comment]
> > @mikkorantalainen https://github.com/hugemce/hugemce/blob/main/modules/sugar/src/demo/ts/ephox/sugar/demo/Demo.ts indeed looks like almost everything could be done natively. Only CSS is maybe cleaner there than with native properties. The question is, why does Sugar then exist? For old browsers?
> 
> 
> 
> I think you meant https://github.com/hugemce/hugemce/blob/02f35e9a88d0b5156d5680af9eb7dc6d1f8f9c3c/modules/sugar/src/demo/ts/hugemce/sugar/demo/Demo.ts because that URL returns HTTP status 404.
> 
> 
> 
> I think the whole Sugar stuff is about the original developer really liking functional languages such as Haskell and they simply wanted to use wrapper that allowed to use more functional-like syntax. However, it causes both extra download and runtime penalty so I think it would make a lot more sense to get rid of such sugar.
> 
> 
> 
> If TypeScript were smart enough to actually implement this as pure syntax sugar and the compiled version had none of this crap, I would be perfectly okay with using the Sugar wrapper if somebody actually likes it. I would personally much prefer native JavaScript (ES6+ because it's readable and works with real world browsers) over any TypeScript even for the original source code.

Thank you for the link; the one referencing the main branch didn't work anymore since the ephox->hugemce replace. For me, it's also weird to do `Module.function(element, whatever`, going to native object-oriented element.browser_function would be better, yeah.

**Comment by carlosmintfan** [comment]
Do you think HugeMCE could be a trademark violation although it doesn't contain the word "Tiny" because it still contains the MCE part, has the same length and could be confused if one hears both something about TinyMCE and HugeMCE?

**Comment by mikkorantalainen** [comment]
I'm not a lawyer but I think trademark law is about "could a rational consumer mistake product X to be produced by the original manufacturer owning the trademark?" and the trademarks are "TinyMCE" and "Tiny". I would think that no rational customer would assume that "HugeMCE" is either of those.

**Comment by carlosmintfan** [comment]
Yeah...what about HugeRTE?

**Comment by carlosmintfan** [comment]
For those who are only subscribed to this issue and haven't noticed my announcements, HugeRTE is up at npm and composer already. How fast time goes by...that was start of this month, now it's end already. I don't have much time currently, but I'm going to have more time in about a month from now. I've detected an issue with the composer packaging: You have to specify `dev-main` as the version to use. I'll look how to fix it, but it can take some time until I get to it. I also have to improve the awful website, of course...and, when I have time, I'm planning to fork two more JS libraries, not because of licensing issues, but because they aren't maintained anymore – but I won't tell you yet which I mean. :)

**Comment by renoth** [comment]
Will there be zip releases? What about Webjars? 
I dont use npm or any other JS package manager

**Comment by rezist** [comment]
> Will there be zip releases? What about Webjars? I dont use npm or any other JS package manager

+1

**Comment by carlosmintfan** [comment]
You can also get a zip from https://github.com/hugerte/hugerte-dist/releases/tag/v1.0.4.

**Comment by akemmanuel** [comment]
I would use your fork if you make it work for react. It would be very kind if you implement it @carlosmintfan

**Comment by carlosmintfan** [comment]
Yes, it will follow, @akemmanuel. I‘ll also fork the jQuery integration.

**Comment by carlosmintfan** [comment]
Closing and locking this long issue as new questions should be asked in discussions. Many thanks for your tips and collaboration. @mikkorantalainen I agree with your three removal points of https://github.com/hugerte/hugerte/issues/1#issuecomment-2095512058. If there are any breaking changes you would like, any things you think could get removed to make the editor more lightweight, please tell me so in an issue or discussion. For bugs please open issues here even if you already reported them to TinyMCE. As for there still being an issue with the images upload handler I‘ll try to investigate, though a PR would be very welcomed.
Next things are publishing the React integration which I‘ve half or more finished already. I‘m not a React developer so for improvements, PRs will be welcomed after I have published it. Then, the Svelte integration. That‘s the framework I use. Then, Angular. I don’t know how to use this framework except for some samples I let ChatGPT generate for me. Not planning to work with it, but porting the integration from TinyMCE to Angular, yes, I’ll do it. But if you then want improvements, please PR if possible.
The Ruby on Rails integration is maintained by a third-party developer but linked to from the TinyMCE docs. Following the TinyMCE 7 license change to GPL it has also changed its license. I don’t know how to use Rails. I‘m planning to contact the developer if he also wants to make a package for HugeRTE. Otherwise, if anybody else wants to do it, create a discussion or email me admin@hugerte.org if you want to speak privately first.
I‘m planning to create a new repo with the imagetools plugin from TinyMCE 5 copied this month. A separate repo because it will need to be LGPL, so not mixed in this repo. LGPL is not MIT, but better than GPL, and I think having this plugin LGPL-licensed is better than not having it. It is very helpful.
**If anybody has a good knowledge of the internals of the TinyMCE codebase and a good knowledge of security and wants to help me for free with checking if a CodeQL alert is valid etc. please email me at admin@hugerte.org.**

**Comment by carlosmintfan** [comment]
@renoth @rezist If you think Webjars would be a plus, please [create a new discussion](https://github.com/orgs/hugerte/discussions/new/choose). But when googling "HugeRTE", I encounter some `org.webjars.npm` already. I'm not familiar in that ecosystem so let me know in a discussion if you thing any addition would be a benefit.
